import type { Route } from '@/types';
import puppeteer from '@/utils/puppeteer';

export const route: Route = {
    path: '/for-you',
    name: 'For You',
    maintainers: ['ResseandMia'],
    handler: async (ctx) => {
        const url = 'https://web.swipeinsight.app/app/for-you';

        const browser = await puppeteer();
        const page = await browser.newPage();
        await page.goto(url, { waitUntil: 'networkidle0', timeout: 120000 });

        // 滚动页面加载更多内容
        await page.evaluate(async () => {
            await new Promise<void>((resolve) => {
                let count = 0;
                const timer = setInterval(() => {
                    window.scrollBy(0, 1200);
                    count++;
                    if (count > 10 || (document.documentElement.scrollHeight - window.scrollY) < 1600) {
                        clearInterval(timer);
                        resolve();
                    }
                }, 600);
            });
        });

        // 提取卡片信息
        const items = await page.$$eval('article, .MuiCard-root, a[href^="http"]', (nodes) => {
            const getText = (el: Element | null) => (el ? (el.textContent || '').trim() : '');
            const out: { title: string; link: string; summary?: string; image?: string }[] = [];

            nodes.forEach((n) => {
                const a = n.querySelector('a[href^="http"]');
                if (!a) return;

                const link = (a.getAttribute('href') || '').trim();
                if (!link) return;

                let title = '';
                const h = n.querySelector('h1, h2, h3');
                title = getText(h) || getText(a) || getText(n);
                if (!title || title.length < 6) return;

                const p = n.querySelector('p');
                const summary = getText(p);

                const img = n.querySelector('img');
                const image = img ? (img.getAttribute('src') || '').trim() : '';

                out.push({ title, link, summary, image });
            });

            const map = new Map<string, any>();
            out.forEach((x) => !map.has(x.link) && map.set(x.link, x));
            return Array.from(map.values()).slice(0, 50);
        });

        await page.close();
        await browser.close();

        ctx.set('data', {
            title: 'SwipeInsight - For You',
            link: url,
            description: 'Auto-generated by RSSHub (Puppeteer)',
            item: items.map((i) => ({
                title: i.title,
                link: i.link,
                description: i.summary,
                guid: i.link,
                enclosure_url: i.image || undefined,
                enclosure_type: i.image ? 'image/jpeg' : undefined,
            })),
        });
    },
};

